name: blackforge

x-beekeeper:
  public_host: blackforge.vladas.xyz

services:
  ui:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: registry.tailf87cbe.ts.net/blackforge-ui:${VERSION}
    ports:
      - "8087:80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--spider", "http://127.0.0.1/"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
