[package]
description = "Graphical mod manager for Valheim"
edition.workspace = true
license.workspace = true
name = "blackforge"
repository.workspace = true
version.workspace = true

# The command line crate owns the `blackforge` file name in the target folder.
[[bin]]
name = "blackforge-gui"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
blackforge-api = { workspace = true }
blackforge-core = { workspace = true }
chrono = { workspace = true }
dotenvy = { workspace = true }
gethostname = { workspace = true }
hilen = { workspace = true, features = ["login"] }
image = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
timeago = { workspace = true }
tokio = { workspace = true }

[build-dependencies]
winresource = { workspace = true }

[package.metadata.deb]
name = "blackforge-gui"
maintainer = "Vladas Zakrevskis"
assets = [
    ["target/release/blackforge-gui", "usr/bin/blackforge-gui", "755"],
    ["../../target/linux-stage/blackforge.desktop", "usr/share/applications/blackforge.desktop", "644"],
    ["../../target/linux-stage/blackforge.png", "usr/share/icons/hicolor/512x512/apps/blackforge.png", "644"],
]
